server:
   port: ${PORT:9080}
application:
   name: ^project.artifactId^
   description: ^project.name^
   version: ^project.version^
eureka:
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://${DISCOVERY_HOST:localhost}:${DISCOVERY_PORT:8761}/eureka/}

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: customer
          uri: lb://customer
          predicates:
            - Path=/api/customers/**
        - id: loan
          uri: lb://loan
          predicates:
            - Path=/api/loanapplications**
        - id: search
          uri: lb://loan
          predicates:
            - Path=/search**
